name: BLIKTECH
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7223416
  brandStrength: 0.9790547
  lightness: 1
  brandColors:
    - '#2C2C2B'
    - '#C0D2EA'
    - '#6081BD'
    - '#AF867F'
    - '#26B0E4'
  rhythmicContrast: 1
typography_spectrum: 0.2787325
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
