analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8222342
  brandStrength: 0.579475277569145
  lightness: 0.7513427
  brandColors:
    - '#DAE6F6'
    - '#2F3032'
    - '#8EAFDC'
    - '#C59378'
    - '#7A7B73'
  rhythmicContrast: 0.9612775
typography_spectrum: 0.2787325
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9575725
favicon: null
name: BLIKTECH
