favicon: null
name: BLIKTECH
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7585056459065527
  brandStrength: 0.579475277569145
  lightness: 0.8058045194484293
  brandColors:
    - '#DAE6F6'
    - '#2F3032'
    - '#8EAFDC'
    - '#C59378'
    - '#7A7B73'
  rhythmicContrast: 0.961277529830113
typography_spectrum: 0.006734318332746625
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9208037776406854
analytics:
  twitter: null
  google: null
  facebook: null
